name: Deploy App to GKE

on:
  workflow_run:
    workflows: ["Deploy GCP Infra using Terraform"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install gcloud CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk

      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials demo-gke-cluster --region us-central1

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
